server:
  port: 7003



eureka:
  instance:
    hostname: eureka7003.com  #localhost
  client:
    register-with-eureka: false   #为false 表示是否向eureka服务端注册自己
    fetch-registry: false         #为false 表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

