server:
  port: 8013

mybatis:
  type-aliases-package: com.liaokuo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test3?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    service-url:
#      单机：
#      defaultZone: http://eureka7001.com:7001/eureka/
#      集群：
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:   #更改Eureka实例ID
    instance-id: springcloud-provider-dept-8013

#info配置
info:
  app.name: liaokuo.springcloud
  company.name: liaokuo.mxoop.com
