server:
  port: 7001



eureka:
  instance:
    hostname: eureka7001.com  #localhost
  client:
    register-with-eureka: false   #为false 表示是否向eureka服务端注册自己
    fetch-registry: false         #为false 表示自己为注册中心
    service-url:
#      单机：
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

